
model_type: "isolation_forest"

metadata:
  name: "graph model 1.2"
  version: "v2.0"
  description: "Isolation forest and UMAP trained on graph_pipeline_v1_0 with higher n_neighbors"

config:
  data: "data/graph_pipeline_v1_0/graph_pipeline_all.csv"
  outfile_dir: "results/graph_model1_2"
  random_seed: 42
  ignore_cols:
    - "userId"

  umap:
    n_neighbors: 30
    min_dist: 0.3
    metric: "euclidean"

