FROM python:3.13

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config/ ./config
COPY data/ ./data
COPY src/ ./src

ENTRYPOINT ["python", "-m", "src.model.umap"]

CMD []