FROM python:3.13

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /src ./src
COPY /config ./config
COPY /data ./data

ENTRYPOINT ["python", "-m", "src.model.isolation_forest_baseline"]
CMD []