"""
The Streamlit application that visualizes the project.
"""

import streamlit as st
import pandas as pd

def intro():
    st.title("Youtube User Anomaly Detection")
    linkedin_url = "https://www.linkedin.com/in/jonathan-tran-b405301ba/"
    st.write("by [Jonathan Tran](%s)" % linkedin_url)
    st.write("An unsupervised learning model that detects unusual commenting behavior from potential bots")
    st.image("./public/img.png")
    
    sora_url = "https://openai.com/index/sora-2/"
    st.write("The ever-growing problem of our generation in the age of AI has been \
        the ability to discern what is reality, recently exemplified with \
        viral videos generated by [Sora 2](%s). Its near-realism, though an impressive \
        feat of engineering, should also raise concerns with the potential use \
        of it to deceive audiences." % sora_url)
    st.markdown("""
    My project takes particular focus on user comments on political content on YouTube for a two main reasons:
    1. It's a niche that tends to attract lots of user activity and discourse.
    2. It's a topic that likely serves as a target for bots.
    """)
    book_url = "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/"
    st.write("The idea came to mind as a fun project a week prior to writing this :) \
        What started as an opportunity to explore unsupervised learning became \
        an indispensible experience in learning MLOps practices, guided by [Chip Huyen's \
        'Designing Machine Learning Systems' (2022)](%s)" % book_url)

def model():
    from model import display_model_page
    display_model_page()

def app():
    st.set_page_config(layout="wide")
    intro()
    model()

app()